version: '3'
services:
  php:
    build: .
    ports:
      - "80:80"
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
    driver: local
